export const CITY_MAP: Record<string, { city: string; countryCode: string }> = {
  // Asia destinations
  HND: { city: 'Tokyo', countryCode: 'JP' },
  NRT: { city: 'Tokyo', countryCode: 'JP' },
  KIX: { city: 'Osaka', countryCode: 'JP' },
  HKG: { city: 'Hong Kong', countryCode: 'HK' },
  ICN: { city: 'Seoul', countryCode: 'KR' },
  SIN: { city: 'Singapore', countryCode: 'SG' },
  BKK: { city: 'Bangkok', countryCode: 'TH' },
  CNX: { city: 'Chiang Mai', countryCode: 'TH' },
  TPE: { city: 'Taipei', countryCode: 'TW' },
  KUL: { city: 'Kuala Lumpur', countryCode: 'MY' },
  MNL: { city: 'Manila', countryCode: 'PH' },
  SGN: { city: 'Ho Chi Minh City', countryCode: 'VN' },
  HAN: { city: 'Hanoi', countryCode: 'VN' },
  DPS: { city: 'Bali', countryCode: 'ID' },
  CGK: { city: 'Jakarta', countryCode: 'ID' },
  BOM: { city: 'Mumbai', countryCode: 'IN' },
  DEL: { city: 'New Delhi', countryCode: 'IN' },
  PUS: { city: 'Busan', countryCode: 'KR' },

  // Europe
  LHR: { city: 'London', countryCode: 'GB' },
  LGW: { city: 'London', countryCode: 'GB' },
  CDG: { city: 'Paris', countryCode: 'FR' },
  ORY: { city: 'Paris', countryCode: 'FR' },
  FRA: { city: 'Frankfurt', countryCode: 'DE' },
  AMS: { city: 'Amsterdam', countryCode: 'NL' },
  MAD: { city: 'Madrid', countryCode: 'ES' },
  BCN: { city: 'Barcelona', countryCode: 'ES' },
  FCO: { city: 'Rome', countryCode: 'IT' },
  MXP: { city: 'Milan', countryCode: 'IT' },
  MUC: { city: 'Munich', countryCode: 'DE' },
  ZRH: { city: 'Zurich', countryCode: 'CH' },
  GVA: { city: 'Geneva', countryCode: 'CH' },
  VIE: { city: 'Vienna', countryCode: 'AT' },
  DUB: { city: 'Dublin', countryCode: 'IE' },
  LIS: { city: 'Lisbon', countryCode: 'PT' },
  ATH: { city: 'Athens', countryCode: 'GR' },
  PRG: { city: 'Prague', countryCode: 'CZ' },
  WAW: { city: 'Warsaw', countryCode: 'PL' },
  CPH: { city: 'Copenhagen', countryCode: 'DK' },
  ARN: { city: 'Stockholm', countryCode: 'SE' },
  OSL: { city: 'Oslo', countryCode: 'NO' },
  HEL: { city: 'Helsinki', countryCode: 'FI' },
  IST: { city: 'Istanbul', countryCode: 'TR' },

  // Middle East
  DXB: { city: 'Dubai', countryCode: 'AE' },
  AUH: { city: 'Abu Dhabi', countryCode: 'AE' },
  DOH: { city: 'Doha', countryCode: 'QA' },
  TLV: { city: 'Tel Aviv', countryCode: 'IL' },

  // Latin America
  MEX: { city: 'Mexico City', countryCode: 'MX' },
  CUN: { city: 'Cancun', countryCode: 'MX' },
  BOG: { city: 'Bogota', countryCode: 'CO' },
  LIM: { city: 'Lima', countryCode: 'PE' },
  SCL: { city: 'Santiago', countryCode: 'CL' },
  EZE: { city: 'Buenos Aires', countryCode: 'AR' },
  GRU: { city: 'Sao Paulo', countryCode: 'BR' },
  GIG: { city: 'Rio de Janeiro', countryCode: 'BR' },

  // Oceania
  SYD: { city: 'Sydney', countryCode: 'AU' },
  MEL: { city: 'Melbourne', countryCode: 'AU' },
  BNE: { city: 'Brisbane', countryCode: 'AU' },
  AKL: { city: 'Auckland', countryCode: 'NZ' },
  NAN: { city: 'Nadi', countryCode: 'FJ' },

  // Africa
  JNB: { city: 'Johannesburg', countryCode: 'ZA' },
  CPT: { city: 'Cape Town', countryCode: 'ZA' },
  NBO: { city: 'Nairobi', countryCode: 'KE' },
  CMN: { city: 'Casablanca', countryCode: 'MA' },

  // US origins
  ATL: { city: 'Atlanta', countryCode: 'US' },
  DEN: { city: 'Denver', countryCode: 'US' },
  DFW: { city: 'Dallas', countryCode: 'US' },
  EWR: { city: 'New York', countryCode: 'US' },
  IAD: { city: 'Washington, D.C.', countryCode: 'US' },
  JFK: { city: 'New York', countryCode: 'US' },
  LAX: { city: 'Los Angeles', countryCode: 'US' },
  MIA: { city: 'Miami', countryCode: 'US' },
  MSP: { city: 'Minneapolis', countryCode: 'US' },
  ORD: { city: 'Chicago', countryCode: 'US' },
  SAN: { city: 'San Diego', countryCode: 'US' },
  SEA: { city: 'Seattle', countryCode: 'US' },
  SFO: { city: 'San Francisco', countryCode: 'US' },
  BOS: { city: 'Boston', countryCode: 'US' },
  PHX: { city: 'Phoenix', countryCode: 'US' },
  PDX: { city: 'Portland', countryCode: 'US' },
  HNL: { city: 'Honolulu', countryCode: 'US' },
  SJC: { city: 'San Jose', countryCode: 'US' },
  AUS: { city: 'Austin', countryCode: 'US' },
  LAS: { city: 'Las Vegas', countryCode: 'US' },
};
